todo 관련 controller, model & 프론트 약간만듬
2chanhaeng/codingon-kdt-web7-project2-team2 pull request #10
Opened 2023-06-02 06:34 UTC by DaeyongGwon

2023-06-02 06:34 UTC, DaeyongGwon commented
PR 확인해주세용!

2023-06-02 07:44 UTC, 2chanhaeng requested changes
수고하셨습니다!
요청한 사항만 변경해주세요!

2023-06-02 07:44 UTC, 2chanhaeng commented on controller/todo.ts
> +    console.log(req.body);
콘솔 로그 지워 주세요!

2023-06-02 07:44 UTC, 2chanhaeng commented on models/todo.ts
변한 건 없는데 포매터 차이 때문에 커밋된 것 같습니다
checkout 해주세요!

2023-06-02 08:27 UTC, 2chanhaeng commented
같은 곳에 라우터를 추가해서 컨플릭트가 나서 둘다 머지했습니다~

2023-06-02 10:07 UTC, 2chanhaeng commented on models/todo.ts
제가 했습니다~

2023-06-02 10:07 UTC, merged

2023-06-03 03:33 UTC, DaeyongGwon commented on models/todo.ts
넵

2023-06-03 03:37 UTC, DaeyongGwon commented on controller/todo.ts
> +    console.log(req.body);
네