public/js/todo/daily.js 파일 api연결, 하영님이 작성한 ejs, css코드 가져옴, todo update, todo-comment create 기능 추가.
2chanhaeng/codingon-kdt-web7-project2-team2 pull request #37
Opened 2023-06-12 06:53 UTC by DaeyongGwon

- public/js/todo/daily.js 코드,  views/todo/daily.ejs 코드, public/style/todo/daily.css 코드
-    오늘의 투두 페이지 css, ejs파일 수정 (하영님이 주신코드)
-    daily.js 오늘의 투두 페이지 투두 리스트 수정 기능
-    daily.js 오늘의 투두 페이지 투두 comment에서 댓글생성 DB에 저장까지 (ejs파일에 표기는 아직 못함)

2023-06-12 12:04 UTC, 2chanhaeng requested changes
고생하셨습니다! 😄 
요청드린 사항 수정 부탁드립니다.
그리고 절대 코드를 Git 이외의 프로그램으로 복붙해서 공유하지 말아주시길 부탁드립니다.
무조건 컨플릭트 납니다...
dev에 PR 날리듯이 공유할 분께 본인 리포지토리에 PR 날려달라고 하신 후에 머지하시면 됩니다.
복붙으로 코드 공유하면 진짜 100% 컨플릭트 납니다.
제발 부탁드려요...ㅠㅠ

2023-06-12 12:04 UTC, 2chanhaeng commented on views/todocalendar.js
> +var todoradio = document.getElementById("todo-radio");
`var` 키워드는 사용을 지양해주시길 바랍니다.

2023-06-12 12:31 UTC, 2chanhaeng commented on public/js/todo/daily.js
> +    const res = await fetch(`/api/todo/comment/comment/${todoId}`, {
해당 API 수정했습니다.
dev에서 pull 하시고 작업 중인 브랜치에 머지 하신 뒤 해당 API 경로를 `/api/todo/comment/${todoId}`로 변경해주시면 감사하겠습니다!

2023-06-13 00:07 UTC, DaeyongGwon commented on public/js/todo/daily.js
> +    const res = await fetch(`/api/todo/comment/comment/${todoId}`, {
네

2023-06-13 00:11 UTC, DaeyongGwon commented on views/diary.ejs
> +        <img src="<%= feel %>" alt="" / style="width: 250px">
.emotion-img 클래스로 스타일 임시로 지정해놨습니다!

2023-06-13 00:11 UTC, DaeyongGwon commented on views/todo/daily.ejs
> +    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
제거완료

2023-06-13 00:11 UTC, DaeyongGwon commented on views/todocalendar.js
> +var todoradio = document.getElementById("todo-radio");
아 임시로 작성하던 코드라서 전체 제거 하겠습니다.

2023-06-13 00:12 UTC, DaeyongGwon commented on public/js/todo/daily.js
> +    alert("댓글 내용을 입력해주세요.");
넹 그냥 내용을 입력해주세요. 문구로 변경할게요.

2023-06-13 16:16 UTC, merged